# Numpy

Numpy es la biblioteca central para computación cientifica en Python. Proporciona un objeto de matriz multidimensional de alto rendimiento y herramientas para trabajar con estas matrices.

Tutorial original: http://cs231n.github.io/python-numpy-tutorial/

## Arrays

Una matriz numpy es una cuadrícula de valores, todos del mismo tipo, y está indexada por una tupla de enteros no negativos. El número de dimensiones es el rango de la matriz; la forma de una matriz es una tupla de enteros que da el tamaño de la matriz a lo largo de cada dimensión.

Podemos inicializar matrices numpy desde listas anidadas de Python y acceder a elementos mediante corchetes:

In [1]:
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])
len(b)

(2, 3)
1 2 4


2

Numpy también provee muchas funciones para crear arrays:

In [4]:
import numpy as np

a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [6]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [7]:
c = np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [10]:
d = np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
e = np.random.random((2,2))
print(e)

[[0.6958414  0.8937636 ]
 [0.77727119 0.91893154]]


Se puede obtener mas información sobre otros metodos y creación de arrays en la siguiente paguina:
https://docs.scipy.org/doc/numpy/user/basics.creation.html#arrays-creation 

## Array Indexing
Numpy ofrece varias formas de indexar matrices.

**Slicing:** Al igual que en las listas de Python, los arreglos numpy se puede hacer sliced. Dado que las matrices pueden ser multidimensionales, debe especificar un sector para cada dimensión de la matriz:

In [13]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
b = a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [15]:
print(a[0,1])
a[0][1]

2


2

In [16]:
b[0,0] = 77
print(a)

[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


También puede mezclar la indexación de enteros con la indexación de segmentos. Sin embargo, hacerlo producirá una matriz de rango más bajo que la matriz original.

In [17]:
import numpy as np

a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
row_r1 = a[1,:]
row_r2 = a[1:2,:]
print(row_r1,row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [19]:
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print(col_r1,col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**Integer array indexing** Cuando indexa en matrices numpy utilizando la segmentación. la vista de matriz resultante siempre será una sub-arreglo de la matriz original. En contraste, la indexación de matrices enteras le permite construir matricesarbitrarias utilizando los datos de otra matriz. Aqui hay un ejemplo:

In [21]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [32]:
print(a[[0,1,2],[0,1,0]])

[1 4 5]


In [35]:
print(np.array([a[0,0],a[1,1],a[2,0]]))

[1 4 5]


In [36]:
print(a[[0,0],[1,1]])

[2 2]


In [38]:
print(np.array([a[0,1],a[0,1]]))

[2 2]


Un truco útil con la indexación de matrices de enteros es seleccionar o mutar un elemento de cada fila de una matriz

In [39]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [40]:
b = np.array([0,2,0,1])
print(b)

[0 2 0 1]


In [41]:
print(a[np.arange(4),b])

[ 1  6  7 11]


In [43]:
a[np.arange(4),b] += 10
print(a)

[[21  2  3]
 [ 4  5 26]
 [27  8  9]
 [10 31 12]]


**Boolean array indexing:** La indexación de matriz booleana le permite seleccionar elementos arbitrarios de una matriz. Con frecuencia, este tipo de indexación se utiliza para seleccionar los elementos de una matriz que sastifacen alguna condición. Aqui hay un ejemplo: 

In [45]:
import numpy as np

a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [46]:
bool_idx = (a>2)
print(bool_idx)
a[bool_idx]

[[False False]
 [ True  True]
 [ True  True]]


array([3, 4, 5, 6])

In [47]:
print(a[bool_idx])

[3 4 5 6]


In [48]:
print(a[a>2])

[3 4 5 6]


En este enlace encuentra más información sobre indexación:  https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html

Cada matriz numpy es una cuadricula de elementos del mismo tipo. Numpy proporciona un gran conjunto de tipos de datos numéricos que pueden utilizar para construir matrices. Numpy intenta adicinar un tipo de datos cuando crea una matriz, pero las funciones que construyen matrices generalmente también incluyen un argumento opcional para especificar explicitamente el tipo de datos. Auí un ejemplo:

In [49]:
import numpy as np

x = np.array([1,2])
print(x.dtype)

int32


In [50]:
x = np.array([1.0,2.0])
print(x.dtype)

float64


In [51]:
x = np.array([1,2],dtype=np.int8)
print(x.dtype)

int8


## Array math
Las funciones matemáticas básicas funcionan de manera elemental en los arreglos, y están disponibles como sobrecargas de operador y como funciones en el módulo numpy:

In [52]:
import numpy as np

x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)

print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [53]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [54]:
print(x)
print(y)
print(x*y)
print(np.multiply(x,y))

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [55]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [56]:
print(np.sqrt(x))
x**(1/2)

[[1.         1.41421356]
 [1.73205081 2.        ]]


array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

* Es una multiplicación por elementos, no una multiplicación de matrices. En su lugar, usamos la función **dot** para calcular los productos internos de los vectores, para multiplicar un vector por una matriz y para multiplicar las matrices. dot está disponible como una función en el módulo numpy y como un método de instancia de objetos de matriz:

In [57]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x.dot(y))

v = np.array([9,10])
w = np.array([11,12])

print(v.dot(v))
print(np.dot(v,w))

[[19 22]
 [43 50]]
181
219


In [58]:
print(x.dot(v))
print(np.dot(x,y))

[29 67]
[[19 22]
 [43 50]]


Numpy proporciona muchas funciones útiles para realizar cálculos en arreglos; una de las más útiles es **sum:**

In [59]:
import numpy as np

x = np.array([[1,2],[3,4]])
print(x)

[[1 2]
 [3 4]]


In [60]:
print(np.sum(x))

10


In [61]:
print(np.sum(x,axis=0))

[4 6]


In [62]:
print(np.sum(x,axis=1))

[3 7]


Más docuemntación sobre funciones que provee Numpy en: https://docs.scipy.org/doc/numpy/reference/routines.math.html